name: Assignment SAST 

on:
  push:
    branches: ["sast"]
  pull_request:

jobs:
  semgrep:
    name: Run SAST Semgrep
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Semgrep
        run: |
          pip install semgrep

      - name: SAST
        continue-on-error: true
        run: |
          semgrep scan
          --config=p/owasp-top-ten
          --config=p/php
          --sarif --output=semgrep-results.sarif

      - name: Upload SAST to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-results.sarif