name: Assignment SAST 

on:
  push:
    branches: ["SCA"]
  pull_request:

jobs:
  semgrep:
    name: Run SAST Semgrep
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Semgrep
        run: |
          pip install semgrep

      - name: SAST
        continue-on-error: true
        run: |
          semgrep scan
          --config=p/owasp-top-ten
          --config=p/php

  trivy:
    name: Run SCA Trivy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'